### ISSUE TITLE
CRLF is not supported

### ISSUE THREAD

**Issue by Kilenaitor** [hhvm/fbmarkdown#5]
Rendering of blockquotes is currently broken. No matter how many newlines exist after the blockquote line ends it still rendered as part of that blockquote. 

**Example 1**
Raw:
<img width="896" alt="screen shot 2018-04-30 at 1 17 10 am" src="https://user-images.githubusercontent.com/4632233/39419337-41f55a42-4c14-11e8-9169-0c9ad6e4edae.png">

Rendered:
<img width="264" alt="screen shot 2018-04-30 at 1 17 20 am" src="https://user-images.githubusercontent.com/4632233/39419338-420f77e2-4c14-11e8-8a0e-8b08bd148455.png">

**Example 2**

Raw: 
<img width="900" alt="screen shot 2018-04-30 at 1 18 00 am" src="https://user-images.githubusercontent.com/4632233/39419357-605c1c1e-4c14-11e8-9721-9cc01cabbe0d.png">

Rendered:
<img width="334" alt="screen shot 2018-04-30 at 1 18 09 am" src="https://user-images.githubusercontent.com/4632233/39419358-6073edee-4c14-11e8-8539-9637004d7e81.png">

---

Relevant render function

```php
private function markdownToHTML(string $markdown): string {
    $ctx = (new Markdown\ParserContext())->enableHTML_UNSAFE();
    $ast = Markdown\parse($ctx, $markdown);

    $html =
      (new Markdown\HTMLRenderer(new Markdown\RenderContext()))->render($ast);

    return $html;
  }
```

---

Raw input: 

```
Blockquotes are broken. 

> Hello I am a blockquote. 

Hello I am not a blockquote. I should come after.
```

HTML output from render: 

```html
<p>Blockquotes are broken.</p>
<blockquote>
<p>Hello I am a blockquote.

Hello I am not a blockquote. I should come after.</p>
</blockquote>
```

**Comment by fredemmott** [comment]
Thanks - what version are you using? I'm not able to reproduce the problem with this script, or by attempting to add to unit tests:

https://gist.github.com/fredemmott/95e9e497622891077fd7855a67061a30

**Comment by Kilenaitor** [comment]
Hey Fred. I'm using v1.0; latest version I see on packagist. Actually realized the issue. JSON-encoded the string and printed it out. The one I was getting from the database had Windows-style newlines `\r\n` instead of just the standard `\n`. 

I did a simple 

```php
$markdown = preg_replace('~\r\n?~', "\n", $markdown);
``` 

where `$markdown` is my string and it _was_ properly parsed by `fbmarkdown`. So it looks like it's a thing regarding newlines. Not sure if it's something to fix or at least better document, but yeah; doing the `preg_replace` beforehand fixed it. :)

**Comment by fredemmott** [comment]
Thanks - yep, this is a bug :)

From spec:

> A line ending is a newline (U+000A), a carriage return (U+000D) not followed by a newline, or a carriage return and a following newline.

fbmarkdown incorrectly only accepts newlines as line endings.
